/*
 * machine-launcher
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};


/// struct for typed errors of method [`oauth_callback`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OauthCallbackError {
    Status400(models::ErrorMessage),
    Status401(models::ErrorMessage),
    Status403(models::ErrorMessage),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`oauth_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OauthLoginError {
    Status400(models::ErrorMessage),
    Status401(models::ErrorMessage),
    Status403(models::ErrorMessage),
    UnknownValue(serde_json::Value),
}


pub async fn oauth_callback(configuration: &configuration::Configuration, code: &str, state: &str) -> Result<(), Error<OauthCallbackError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_code = code;
    let p_state = state;

    let uri_str = format!("{}/auth/callback", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("code", &p_code.to_string())]);
    req_builder = req_builder.query(&[("state", &p_state.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<OauthCallbackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn oauth_login(configuration: &configuration::Configuration, ) -> Result<(), Error<OauthLoginError>> {

    let uri_str = format!("{}/auth/login", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<OauthLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

