url = "http://localhost:8080/"

[oidc]
issuer = "https://kanata.jp.auth0.com/"
client_id = "${OIDC_CLIENT_ID}"
client_secret = "${OIDC_CLIENT_SECRET}"
role_attribute_path = "contains(\"https://kanatakita.com/roles\", 'admin')"

[[drivers]]
type = "Debug"
name = "debug"

[[drivers]]
type = "Wol"
name = "wake-on-lan"
mac_addr = "11:22:33:44:55:66"
ip_addr = "192.168.0.1"
