/*
 * machine-launcher
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorMessage {
    #[serde(rename = "error")]
    pub error: String,
}

impl ErrorMessage {
    pub fn new(error: String) -> ErrorMessage {
        ErrorMessage {
            error,
        }
    }
}

