url = "${URL}"

[oidc]
provider_url = "https://kanata.jp.auth0.com/"
client_id = "${AUTH0_CLIENT_ID}"
client_secret = "${AUTH0_CLIENT_SECRET}"
role_attribute_path = "contains(\"https://kanatakita.com/roles\", 'admin')"

[[drivers]]
type = "Ipmi"
name = "server01"
server_addr = "192.168.0.22:623"
username = "${IPMI_USERNAME}"
password = "${IPMI_PASSWORD}"

[[drivers]]
type = "Debug"
name = "debug01"
