name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: jdx/mise-action@v2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - run: mise run pre-merge
      - name: Check for uncommitted changes
        run: git diff --exit-code
